# Site settings
title:       Glen Lovett
author:      Glen Lovett
description: "Software Developer"
baseurl:     ""
url:         "https://glenlovett.com" 

# Social Links
github_username:  glenlovett
linkedin_username: glenlovett
repository: https://github.com/glenlovett/glenlovett.github.io

# Build settings
markdown: kramdown
permalink: pretty

excerpt_separator: <!--more-->
